<script>
    function processData() {
        console.log("Start Processing Data");
        a + b;
    }
    try {
        processData();
    }
    catch {
        console.log("Some Exception Occured and handled..!");
    }
    finally {
        console.log("Processing Ended");
    }
    console.log("Some Other tasks");
</script>

<!--Exception means reference error-->